language: java

jdk:
- oraclejdk8

after_success:
  - ./gradlew clean test testIntegration jacocoTestReport
  - ./gradlew jacocoTestReport coveralls


after_failure:
  - ./gradlew clean check --debug
